### PR TITLE
Improve panning, menubar reachable with keys

### PR DESCRIPTION
**Pull request by brenthuisman**
* Make panning faster, here it now matches cursor speed roughly.
* Rotate over gamma with middle mouse button
* Make MenuBar MainMenuBar, which makes it reachable by keyboard.

### CODE REVIEW

**Comment by thorstenhater** [comment]
Good addition, while we are at it, we could make RMB rotate theta.

**Comment by thorstenhater** [comment]
Good addition, while we are at it, we could make RMB rotate theta.

**Comment by brenthuisman** [comment]
That I had a first, but it interferes with the context menu.

**Comment by thorstenhater** [comment]
Yes, that's an issue. We can always mess with the bindings later on.

**Pull request merged**
