### PR TITLE
Glsl lower version

### PR DESCRIPTION
**Pull request by brenthuisman**
Lower GLSL version to 3.20ES, removes need for MESA_GL_VERSION_OVERRIDE hack. Might be convenient for a webby version of Arbor-Gui?

I should have started with `master` I see; the only changes are in `/glsl`.

### CODE REVIEW

**Comment by thorstenhater** [comment]
OpenGL ES is a different profile than OpenGL core and as such not a 'lower' version. Changing only the shaders is incorrect,
OpenGL must be initialised with the proper profile in both the glfw and the imGui setup calls. 

I am extremely hesitant to touch the OpenGL version and profile as especially on MacOS the support for OpenGL is very brittle. The fact that it removes the need to force MESA to a specific version is also not indicative of the impact on native
drivers (AMD/NVIDIA) on Linux.

I think some research is needed before this can be considered.

**Comment by brenthuisman** [comment]
I think then we must put any release on hold until we understand what an optimal profile is. Fiddling with overriding OGL version profiles is not something we should consider, and is also not needed.

Profile 3.20 ES is the most broadly compatible to my knowledge (and required these small syntax changes) and therefore seems like a good fit for the renderer. WebGL 2, based on ES 3.0 (so slightly older in fact), is supported by Safari, indicating that also for Macos it'd be a good fit.

**Comment by thorstenhater** [comment]
That's the whole issue here: There is no optimal profile, since there is a plethora of devices, profiles, drivers, etc

I would be interested in the rationale and sources behind the blanket statement 'do not need to, and should not'.
Similarly: Which platforms support ES 3.20, why is it the 'most broadly compatible'? Again, we need something that
is usable on MacOS and Linux and is supported by ImGUI.
Finally, the fact that a browser is supporting a certain standard says next to nothing about the platform said browser is
running on.

**Comment by brenthuisman** [comment]
After some study and trial and error w/ @thorstenhater, we've discovered that setting

```
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);            // 3.0+ only
```

in Linux as well solves the issue. Also, we can safely bump to OpenGL 4.1, which is released in 2010, and thus well supported on Linux. Also it is the maximum supported version on Macos, and is supported from Maverick onwards.

**Pull request closed without merging**
